version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  service_b:
    build:
      context: ./service_b
    volumes:
      - /tmp:/tmp
    depends_on:
      - db
    restart: always

  service_a:
    build:
      context: ./service_a
    volumes:
      - /tmp:/tmp
    ports:
      - "8000:8000"
    depends_on:
      - service_b
    restart: always

  write_api:
    build:
      context: ../databaseservices/write_api
    depends_on:
      - db
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://user:password@db/mydatabase

  read_api:
    build:
      context: ../databaseservices/read_api
    depends_on:
      - db
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgres://user:password@db/mydatabase

volumes:
  postgres_data:
