name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Récupère ton code source depuis GitHub

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Configuration de Docker Buildx pour GitHub Actions

    - name: Install Docker Compose
      run: |
        # Installer Docker Compose
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Vérification que Docker Compose est bien installé

    - name: Build Docker images with docker-compose
      run: |
        # Construire les images Docker en utilisant le chemin correct pour le fichier docker-compose.yml
        docker-compose -f hands_on_microservices/docker-compose.yml build

    - name: Install dependencies in the containers
      run: |
        # Installer les dépendances dans le container via Docker
        docker-compose -f hands_on_microservices/docker-compose.yml run service_a pip install -r /app/requirements.txt
        docker-compose -f hands_on_microservices/docker-compose.yml run service_b pip install -r /app/requirements.txt
