name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  
    - name: Build Docker images with docker-compose
      run: 
        
        # Construire les images Docker
        docker-compose -f docker-compose.yml build

    - name: Install dependencies in the containers
      run: |
        # Installer les dépendances dans le container via Docker
        docker-compose run service_a pip install -r /app/requirements.txt
        docker-compose run service_b pip install -r /app/requirements.txt
